baseurl = "http://localhost:1313/"
title = "SmartRoadSense"
defaultContentLanguage = "en"

#permalinks:
#  news: /:year/:month/:slug/


[Languages]

[Languages.en]
languageName = "English"
languageCode = "en-us"
weight = 1
[Languages.en.params]
linkedin = "english-link"

[Languages.it]
languageName = "Italiano"
languageCode = "it"
weight = 2
[Languages.it.params]
linkedin = "lien-francais"
[Languages.it.navigation]
help  = "Aide"
