baseurl = "http://localhost:1313/"
title = "SmartRoadSense"
defaultContentLanguage = "en"
enableMissingTranslationPlaceholders = true

[permalinks]
news = "/:year/:month/:day/:slug/"

[Languages]

[Languages.en]
languageName = "English"
languageCode = "en-us"
weight = 1

[Languages.it]
languageName = "Italiano"
languageCode = "it"
weight = 2
