baseurl = "http://localhost:1313/"
title = "SmartRoadSense"
defaultContentLanguage = "en"
enableMissingTranslationPlaceholders = true
timeout = 100000
disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
news = "/:section/:year/:month/:slug/"

[Languages]

[Languages.en]
languageName = "English"
languageCode = "en-us"
weight = 1

[Languages.it]
languageName = "Italiano"
languageCode = "it"
weight = 2
